title: Jerome's Tech Blog
tagline: Musings and learnings from my journey in tech.
description: Musings and learnings from my journey in tech.

remote_theme: amitmerchant1990/reverie

url: https://tech.dailyfuneral.net
enforce_ssl: https://tech.dailyfuneral.net
timezone: Pacific/Auckland
locale: en_NZ

author:
  name: Jerome Brown
  url: https://tech.dailyfuneral.net
  picture: /images/memoji.png
avatar: /images/memoji.png

footer-links:
  email:
  github: oWretch
  instagram:
  linkedin: oWretch
  rss: rss
  twitter: oWretch
  stackoverflow:
  youtube: # channel/<your_long_string> or user/<user-name>

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:categories/:title:output_ext

version: v1.2.0

kramdown:
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

include: ["_pages"]

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
